// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/health': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/health.get').default>>>>
    }
    '/api/tasks/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tasks/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tasks/[id].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tasks/[id].put').default>>>>
    }
    '/api/tasks': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tasks/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tasks/index.post').default>>>>
    }
    '/_openapi.json': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/nitropack@2.13.1/node_modules/nitropack/dist/runtime/internal/routes/openapi').default>>>>
    }
    '/_scalar': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/nitropack@2.13.1/node_modules/nitropack/dist/runtime/internal/routes/scalar').default>>>>
    }
    '/_swagger': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/nitropack@2.13.1/node_modules/nitropack/dist/runtime/internal/routes/swagger').default>>>>
    }
  }
}
export {}